name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
  
        - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
    #  run: |
    #    aws s3 sync ./dist/cosplayers s3://gallery-cosplay
      env:
        AWS_S3_BUCKET: 'ivantec'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist/ivantec'


